### ISSUE TITLE
Marshall Internal Server Error

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/marshall_webapp_wiki#172]
Marshall is keeling over with an internal server error.

Investigating the webapp apache logs shows the following.  Seems to have been happening a lot since 15th August.

```
[Tue Aug 20 18:24:24 2019] [error] [client ::1] mod_wsgi (pid=93400): Exception occurred processing WSGI script '/misc/pessto/git_repos/marshall_webapp/apache/htdocs/marshall'.
[Tue Aug 20 18:24:24 2019] [error] [client ::1] Traceback (most recent call last):
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/mod_wsgi/server/__init__.py", line 1300, in handle_request
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     return self.application(environ, start_response)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/paste/urlmap.py", line 203, in __call__
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     return app(environ, start_response)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     response = self.invoke_subrequest(request, use_tweens=True)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     response = handle_request(request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 165, in toolbar_tween
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     return handler(request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     response = handler(request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     response = view_callable(context, request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     return view(context, request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     return view(context, request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     return view(context, request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     return view(context, request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     result = view(context, request)
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/home/marshall/.virtualenv/marshall_webapp/lib/python2.7/site-packages/pyramid/config/views.py", line 477, in _class_requestonly_view
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     response = getattr(inst, attr)()
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/marshall_webapp/marshall_webapp/views/views_transients.py", line 114, in get_html
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     htmlContent = transientData.get()
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/marshall_webapp/marshall_webapp/templates/responses/templates_transients.py", line 117, in get
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     maincontent = self._get_object_tickets()
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/marshall_webapp/marshall_webapp/templates/responses/templates_transients.py", line 678, in _get_object_tickets
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     ticketList = self._get_list_of_transient_tickets()
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/marshall_webapp/marshall_webapp/templates/responses/templates_transients.py", line 194, in _get_list_of_transient_tickets
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     transientCrossmatches=self.transientCrossmatches
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/marshall_webapp/marshall_webapp/templates/commonelements/tickets/single_ticket/__init__.py", line 100, in single_ticket
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     transientCrossmatches=transientCrossmatches
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/marshall_webapp/marshall_webapp/templates/commonelements/tickets/single_ticket/tabs/overview.py", line 86, in overview_tab
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     discoveryDataDictionary=discoveryDataDictionary,
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/marshall_webapp/marshall_webapp/templates/commonelements/tickets/single_ticket/ticket_building_blocks/object_info_block.py", line 183, in object_info_block
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     daysPast = dcu.pretty_date(dateAdded)[2:]
[Tue Aug 20 18:24:24 2019] [error] [client ::1]   File "/misc/pessto/git_repos/dryxPython/dryxPython/commonutils/__init__.py", line 253, in pretty_date
[Tue Aug 20 18:24:24 2019] [error] [client ::1]     diff = datetime.now() - date
[Tue Aug 20 18:24:24 2019] [error] [client ::1] TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'

```

**Comment by thespacedoctor** [comment]
fixed - issue with one PS1 source.
